import './PredictionReport.css' 
 
const FEATURE_LABELS = { 
  NDVI: 'NDVI', 
  NDMI: 'NDMI', 
  B04_B02: 'B04 / B02', 
  B04_B11: 'B04 / B11', 
  B11_B12: 'B11 / B12', 
} 
 
function getScore(prediction) { 
  if ( 
    Number.isFinite( 
      Number(prediction?.prospectivity_score) 
    ) 
  ) { 
    return Number( 
      prediction.prospectivity_score 
    ) 
  } 
 
  if ( 
    Number.isFinite( 
      Number(prediction?.probability) 
    ) 
  ) { 
    return ( 
      Number(prediction.probability) * 100 
    ) 
  } 
 
  return null 
} 
 
function downloadReport(prediction) { 
  if (!prediction) return 
 
  const score = getScore(prediction) 
 
  const latitude = 
    Number( 
      prediction.location?.latitude 
    ) 
 
  const longitude = 
    Number( 
      prediction.location?.longitude 
    ) 
 
  const features = 
    prediction.features || {} 
 
  const featureLines = Object.keys( 
    FEATURE_LABELS 
  ) 
    .map((key) => { 
      const value = 
        Number(features[key]) 
 
      return `${FEATURE_LABELS[key]}: ${ 
        Number.isFinite(value) 
          ? value.toFixed(4) 
          : 'N/A' 
      }` 
    }) 
    .join('\n') 
 
  const report = ` 
OREVISION AI 
AI PREDICTION REPORT 
======================================== 
 
STUDY AREA 
Ballari–Vijayanagara–Sandur Iron Ore Belt 
Karnataka, India 
 
LOCATION 
---------------------------------------- 
Latitude:  ${ 
    Number.isFinite(latitude) 
      ? latitude.toFixed(6) 
      : 'N/A' 
  } 
 
Longitude: ${ 
    Number.isFinite(longitude) 
      ? longitude.toFixed(6) 
      : 'N/A' 
  } 
 
 
AI PREDICTION 
---------------------------------------- 
Classification: ${ 
    prediction.classification || 
    'N/A' 
  } 
 
Prospectivity Score: ${ 
    score !== null 
      ? `${score.toFixed(2)}%` 
      : 'N/A' 
  } 
 
 
MODEL 
---------------------------------------- 
Algorithm: ${ 
    prediction.model || 
    'Validated XGBoost' 
  } 
 
Data Source: 
Sentinel-2-derived spectral features 
 
Spatial Resolution: 
10 m 
 
Coordinate Reference System: 
EPSG:32643 
 
 
SENTINEL-2 FEATURES 
---------------------------------------- 
${featureLines} 
 
 
INTERPRETATION 
---------------------------------------- 
${ 
    prediction.interpretation || 
    'The score is an XGBoost model-estimated prospectivity probability based on Sentinel-2-derived spectral features.' 
  } 
 
 
ACADEMIC DISCLAIMER 
---------------------------------------- 
This output is generated for an academic 
mini-project. 
 
The prospectivity score is a model estimate 
and is NOT an iron concentration measurement. 
 
It does NOT confirm the presence of 
underground iron ore. 
 
The system is not a validated geological 
survey result and should not be used for 
real exploration, investment, or land-use 
decisions. 
 
 
Generated by: 
OreVision AI 
 
======================================== 
` 
 
  const blob = 
    new Blob( 
      [report], 
      { 
        type: 'text/plain;charset=utf-8', 
      } 
    ) 
 
  const url = 
    URL.createObjectURL(blob) 
 
  const link = 
    document.createElement('a') 
 
  const safeLat = 
    Number.isFinite(latitude) 
      ? latitude.toFixed(4) 
      : 'location' 
 
  const safeLon = 
    Number.isFinite(longitude) 
      ? longitude.toFixed(4) 
      : 'location' 
 
  link.href = url 
 
  link.download = 
    `OreVision_AI_Prediction_${safeLat}_${safeLon}.txt` 
 
  document.body.appendChild(link) 
 
  link.click() 
 
  document.body.removeChild(link) 
 
  URL.revokeObjectURL(url) 
} 
 
export default function PredictionReport({ 
  prediction, 
}) { 
  if (!prediction) { 
    return null 
  } 
 
  const score = 
    getScore(prediction) 
 
  const classification = 
    prediction.classification || 
    'LOW' 
 
  const features = 
    prediction.features || {} 
 
  return ( 
    <div className="prediction-report-card"> 
 
      <div className="prediction-report-header"> 
 
        <div> 
 
          <div className="eyebrow"> 
            PREDICTION REPORT 
          </div> 
 
          <h3> 
            AI Location Analysis 
          </h3> 
 
        </div> 
 
        <button 
          type="button" 
          className="download-report-button" 
          onClick={() => 
            downloadReport( 
              prediction 
            ) 
          } 
        > 
          Download Report 
        </button> 
 
      </div> 
 
 
      <div className="report-main-result"> 
 
        <div> 
 
          <span> 
            PROSPECTIVITY 
          </span> 
 
          <strong 
            className={ 
              classification.toLowerCase() 
            } 
          > 
            {classification} 
          </strong> 
 
        </div> 
 
 
        <div className="report-score"> 
 
          <span> 
            SCORE 
          </span> 
 
          <strong> 
            {score !== null 
              ? `${score.toFixed(2)}%` 
              : '—'} 
          </strong> 
 
        </div> 
 
      </div> 
 
 
      <div className="report-section"> 
 
        <div className="report-section-title"> 
          LOCATION 
        </div> 
 
        <div className="report-grid"> 
 
          <div> 
            <span> 
              LATITUDE 
            </span> 
 
            <strong> 
              {Number( 
                prediction.location 
                  ?.latitude 
              ).toFixed(6)} 
            </strong> 
          </div> 
 
 
          <div> 
            <span> 
              LONGITUDE 
            </span> 
 
            <strong> 
              {Number( 
                prediction.location 
                  ?.longitude 
              ).toFixed(6)} 
            </strong> 
          </div> 
 
        </div> 
 
      </div> 
 
 
      <div className="report-section"> 
 
        <div className="report-section-title"> 
          SENTINEL-2 FEATURES 
        </div> 
 
        <div className="report-feature-grid"> 
 
          {Object.keys( 
            FEATURE_LABELS 
          ).map((key) => { 
 
            const value = 
              Number(features[key]) 
 
            return ( 
              <div key={key}> 
 
                <span> 
                  {FEATURE_LABELS[key]} 
                </span> 
 
                <strong> 
                  {Number.isFinite( 
                    value 
                  ) 
                    ? value.toFixed(4) 
                    : '—'} 
                </strong> 
 
              </div> 
            ) 
          })} 
 
        </div> 
 
      </div> 
 
 
      <div className="report-section"> 
 
        <div className="report-section-title"> 
          MODEL 
        </div> 
 
        <div className="report-model-grid"> 
 
          <div> 
            <span> 
              ALGORITHM 
            </span> 
 
            <strong> 
              Validated XGBoost 
            </strong> 
          </div> 
 
 
          <div> 
            <span> 
              DATA SOURCE 
            </span> 
 
            <strong> 
              Sentinel-2 
            </strong> 
          </div> 
 
 
          <div> 
            <span> 
              RESOLUTION 
            </span> 
 
            <strong> 
              10 m 
            </strong> 
          </div> 
 
 
          <div> 
            <span> 
              CRS 
            </span> 
 
            <strong> 
              EPSG:32643 
            </strong> 
          </div> 
 
        </div> 
 
      </div> 
 
 
      <div className="report-interpretation"> 
 
        <div className="report-section-title"> 
          INTERPRETATION 
        </div> 
 
        <p> 
          {prediction.interpretation || 
            'The score is an XGBoost model-estimated prospectivity probability based on Sentinel-2-derived spectral features.'} 
        </p> 
 
      </div> 
 
 
      
 
    </div> 
  ) 
}      